#spring:
  #datasource:
   # url:  jdbc:postgresql://localhost:5432/library
    #schema: schema.sql
    #data: data.sql
    #data-username: postgres
    #data-password: postgres
    #tomcat:
     # init-s-q-l:

  #h2:
   # console:
    #  enabled: true
     # path: /h2
spring:
  jpa:
    database: POSTGRESQL
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    jdbc:
      sqlonly: info
