DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
create TABLE BOOKS
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS2GENRES;
create TABLE BOOKS2GENRES
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    bookId   BIGINT,
    FOREIGN KEY (bookId) REFERENCES BOOKS (ID),
    genreId  BIGINT,
    FOREIGN KEY (genreId) REFERENCES GENRES (ID)
);

DROP TABLE IF EXISTS BOOKS2AUTHORS;
create TABLE BOOKS2AUTHORS
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    bookId   BIGINT,
    FOREIGN KEY (bookId) REFERENCES BOOKS (ID),
    authorId BIGINT,
    FOREIGN KEY (authorId) REFERENCES AUTHORS (ID)
);

DROP TABLE IF EXISTS AUTHORS2GENRES;
create TABLE AUTHORS2GENRES
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    authorId   BIGINT,
    FOREIGN KEY (authorId) REFERENCES AUTHORS (ID),
    genreId BIGINT,
    FOREIGN KEY (genreId) REFERENCES GENRES (ID)
);




